# Generated by Django 5.1 on 2024-08-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_habilidades_tecnicas_delete_interesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
